### ISSUE TITLE
Improving decensoring quality of mosaic.

### ISSUE THREAD

**Issue by devilemperor** [deeppomf/DeepCreamPy#100]
You probably noticed that sometimes the program badly removes mosaic censorship from the image.

I made some test with decensoring mosaic and found out, if we repeat decensoring steps 3-4 times, it improving quality dramatically. 

Logic of this idea.
1. Get first decensored image.
2. Replace old original image with new one . 
3. Repeat step 1, four times.

Here is simple and dirty bat script for that. (in the folder decensor_input_original image has to be in PNG format)

```
@echo Off
set repeat_steps=4
set decensor_orig_folder=decensor_input_original
set decensor_out_folder=decensor_output

FOR /L %%i IN (1,1,%repeat_steps%) DO (
  start /WAIT "" "decensor.exe" --is_mosaic=True
  copy /Y %decensor_out_folder%\*.png %decensor_orig_folder%
)
```

Put it in a folder where is the file decensor.exe

It will be great is someone make that patch in python language.

**Comment by deeppomf** [comment]
Seems too hacky to include in official releases. Thanks for the idea though.
