### ISSUE TITLE
Decensoring mosaic gives a crash

### ISSUE THREAD

**Issue by stiv-yakovenko** [deeppomf/DeepCreamPy#106]
Trying to decensor this test picture: 
![mosaic](https://user-images.githubusercontent.com/4163254/52523152-c7445d00-2cc0-11e9-9c7a-169f70c7eb12.png)

application works correctly with green regions, but if there is no green regions and i pass flag --is_mosaic=True, app fails:

![image](https://user-images.githubusercontent.com/4163254/52523166-efcc5700-2cc0-11e9-9e91-2b2dbf11027a.png)

**Comment by Kadantte** [comment]
The app needs you to color the region you want to decensor with green to work otherwise you can't use it. Please check [TROUBLESHOOTING_DECENSORS.md](https://github.com/deeppomf/DeepCreamPy/blob/master/docs/TROUBLESHOOTING_DECENSORS.md).

**Comment by Vaddyl** [comment]
w
