### ISSUE TITLE
How many pictures used in training?

### ISSUE THREAD

**Issue by zhouhang95** [deeppomf/DeepCreamPy#107]
How many pictures used in training?

**Comment by Kadantte** [comment]
As far as I know, he uses this Dataset to train his Model: [Danbooru2018](https://www.gwern.net/Danbooru2018)

**Comment by zhouhang95** [comment]
Maybe not, he says he used crawler.

**Comment by Kadantte** [comment]
See [#64 ](https://github.com/deeppomf/DeepCreamPy/issues/64#issuecomment-435742203)

**Comment by deeppomf** [comment]
100,000 images.
