### ISSUE TITLE
What are the specific requirements for png images?

### ISSUE THREAD

**Issue by Small-Carp** [deeppomf/DeepCreamPy#110]
What are the requirements for PNG images? I used images downloaded from the web and also used (0, 255, 0) green for coloring, but the effect is much worse than the mermaid image given in the code, even no effect.

**Comment by deeppomf** [comment]
Does https://github.com/deeppomf/DeepCreamPy/blob/master/docs/TROUBLESHOOTING_DECENSORS.md help?
