### ISSUE TITLE
I can not install DeepCreamPy

### ISSUE THREAD

**Issue by Woolf2018** [deeppomf/DeepCreamPy#111]
Can not run the program. Because my computer does not support AVX (inte (R) Atom). Write detailed instructions on how to run the program on my computer. Or shoot a video how to do it. Sorry, I translate everything from Russian into English so it becomes more difficult to understand.

**Comment by deeppomf** [comment]
What OS are you running?

**Comment by Woolf2018** [comment]
> На какой ОС вы работаете?

Windows10  64bit

**Comment by deeppomf** [comment]
If neither release binary works on your computer, then you will need to run the code.
You will first need to download Python3 and follow the instructions for running the code in the README.

**Comment by Woolf2018** [comment]
> Если ни один из двоичных выпусков не работает на вашем компьютере, то вам нужно будет запустить код. 
> Сначала вам нужно скачать Python3 и следовать инструкциям по запуску кода в README.

I downloaded pure Python 3.6.7. installed C ++ 2015. Through Python, I launched tenorflow-1.10.0-cp36-cp36m
win_amd64.whi. After this there was a problem, I do not have a file DeepCreamPy-master. There is only the DeepCreamPy_1.3.0-beta_win64 folder itself. Where is the DeepCreamPy-master file?

**Comment by deeppomf** [comment]
You need to clone/download the code in this repo.

**Comment by Woolf2018** [comment]
> Вам нужно клонировать / скачать код в этом репо.
Can you drop the link what and where to download?

**Comment by deeppomf** [comment]
![img](https://user-images.githubusercontent.com/35541366/54033284-e0d2aa80-4181-11e9-8a81-ddbdaa9ffb34.png)
Click on 'Download Zip'
