### ISSUE TITLE
Please tell me about the principle and code analysis of this project.

### ISSUE THREAD

**Issue by Small-Carp** [deeppomf/DeepCreamPy#112]
I am a newbie, I feel that your work is very interesting, I want to learn your thoughts. I hope you can give me a detailed explanation of the relevant principles and documentation of the project source code. Thank you.

**Comment by deeppomf** [comment]
What do you want explained? The project isn't complicated. Everything is done with a few scripts that are self-explanatory.

**Comment by Small-Carp** [comment]
ok,thank you.

**Comment by Kadantte** [comment]
Just check every script and you will get the idea.
