### ISSUE TITLE
Problem with Installing, error message occurs

### ISSUE THREAD

**Issue by snakeBumble** [deeppomf/DeepCreamPy#115]
Hello.

When i double click __decensor.py__ it just says: 

_using Tensorflow backend.
Error: No module named 'tensorflow.python'
could not import modules. Make sure all dependencies are installed._

This is the same Message i got before starting the Installation all over again.
Now i dont know how to open Python in a specific Location to Install the __reqirements.txt__
As I said the Error Message above also accured before i started from the Beginning again by just deleting __DeepCreamPy-master__. I dont know if that was enaugh to have it all reset again.

So now i have a png in __decensor_input__ and a jpg in __decensore_input_original__. I also have __model.h5__ in the models folder. I dont know what to do with __tensorflow-1.10.0-cp36-cp36m-win_amd64.whl__.

I am new to Python and Tensorflow so i dont really know what to do now.
Hope you can help me.
Thanks in advance.

**Comment by Kadantte** [comment]
to install reqirements.txt you need to do it with this CMD : `pip install -r requirements.txt`.
Also create a bat file and put this code on it:
```shell
@echo off
CD /d "%~dp0"
start cmd
```
save it and then copy it to your DeepCreamPy folder then run it it should open the command line in the same path as DeepCreamPy now run this command from it: `pip install -r requirements.txt` and wait until it's done. if have an SSE2 CPU open requirements.txt and remove `﻿tensorflow==1.10.0, tensorboard==1.10.0 ` after u do that download **tensorflow-1.10.0-cp36-cp36m-win_amd64.whl** and copy it into your DeepCreamPy folder the edit requirements.txt again and put `tensorflow-1.10.0-cp36-cp36m-win_amd64.whl` in it and save now you should be ready to run `pip install -r requirements.txt` from your CLI.

**Comment by snakeBumble** [comment]
Oh right. I forgot that it was CMD and not Python where i had to install it. Ok so everything is still installed but it still doesnt work. Thats probably because of the CPU but i dont know what *SSE2* means. [This](http://www.cpu-world.com/CPUs/K10/AMD-Phenom%20II%20X3%20740%20Black%20Edition%20-%20HDZ740WFK3DGI%20(HDZ740WFGIBOX).html) is what i found about the *SSE* from my CPU. Further down on the site under __Architecture / Microarchitecture__ it says that it supports __SSE,SSE2,SSE3__ and __SSE4a__ if i understood that correctly. So it should work based on that. Maybe I did something else wrong?

**Comment by Kadantte** [comment]
You can uninstall with `pip uninstall tensorflow-1.10.0-cp36-cp36m-win_amd64.whl`, since you're new with pip i recommended for you to check [pip User Guide](https://pip.pypa.io/en/stable/user_guide/), and [pip uninstall](https://pip.pypa.io/en/stable/reference/pip_uninstall/).

**Comment by snakeBumble** [comment]
I use Python 3.6.7

**Comment by Kadantte** [comment]
you can if you want.

**Comment by snakeBumble** [comment]
Ok thank you very much for the Help!

**Comment by snakeBumble** [comment]
Ok so now i tried Installing it with __tensorflow-1.10.0-cp36-cp36m-win_amd64.whl__ but in CMD it still said that it installed __tensorboard__ although it is not listed in __requirements.txt__. Something that changed is the "Error Message" that i get from __decensor.py__. I dont know if that really is an Error Mesage but it says:

_Using Tensorflow backend_

There is no output in __decensor_output__ though.

**Comment by Kadantte** [comment]
It's not an Error you need to wait until DCP done with the picture you give it.

**Comment by snakeBumble** [comment]
Yeah I realized it just a few minutes ago. Was too impatient. Thanks for the Help!

**Comment by Kadantte** [comment]
Glade to help :)
