### ISSUE TITLE
Suggestion: supporting jpg, jpeg file

### ISSUE THREAD

**Issue by ccppoo** [deeppomf/DeepCreamPy#121]
I wandered why line 64 exists in decensor.py (valid_formats = {".png", ".jpg", ".jpeg"}) 
because it required only png file-type(line 78) 
and if-case in line  55 fetched other type except png.

So after i removed ".gitignore" file from decnesor_input and changed "and" to "or" 
to check if .jpg, .jpeg still works.

It worked well

![mermaid_collage_copy](https://user-images.githubusercontent.com/46418312/56012831-180c1c80-5d29-11e9-910e-b488825272ce.jpeg)
![mermaid_collage_copy](https://user-images.githubusercontent.com/46418312/56012832-180c1c80-5d29-11e9-94a2-68900a64fb05.jpg)

I'm posting this because only png files is mentioned in USAGE.md

**Comment by marcussacana** [comment]
I think is because the .jpg compression create artifacts in the picture, and a image with many artifacts will be a trouble to the DCP

**Comment by ccppoo** [comment]
> I think is because the .jpg compression create artifacts in the picture, and a image with many artifacts will be a trouble to the DCP

Thanks for your opinion. Maybe I need to learn more about it

**Comment by deeppomf** [comment]
@marcussacana gave the reason.
