### ISSUE TITLE
Where can I find method : is_mosaic ?

### ISSUE THREAD

**Issue by ccppoo** [deeppomf/DeepCreamPy#122]
line 60 in decensor.py ( if self.is_mosaic: )
I've never saw my other test samples satisfying if.self.is_mosaic.
(checked by adding print(" !!!! IF SELF.IS_MOSAIC !!!!!"))
Every image files that I used for sample  self.is_mosaic returns false

So I searched all the imported libraries(Pillow, numpy,os), and this project, and github to check what's inside the method. But most result from python shows this project and it's clones.

This is my best result what I searched from google( python "is_mosaic" )

![capture-2](https://user-images.githubusercontent.com/46418312/56014216-47258c80-5d2f-11e9-8612-4b8fa0f23620.PNG)

from. https://nipy.org/nibabel/reference/nibabel.nicom.html#is-mosaic

is this same code used in decensor.py? I've never seen this site before

**Comment by deeppomf** [comment]
It's defined in config.py

**Comment by ccppoo** [comment]
> It's defined in config.py

parser.add_argument('--is_mosaic', dest='is_mosaic', default='False', type=str2bool, help='true if image has mosaic censoring, false otherwise')

Thanks, I've ever seen this type of method define
