### ISSUE TITLE
This error message pops up when i try to run the binary 

### ISSUE THREAD

**Issue by Flyersfan976** [deeppomf/DeepCreamPy#133]
**DO NOT POST ADULT CONTENT**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
DO NOT POST ADULT CONTENT.

**Installation method**
Did you install DeepCreamPy with the binary?
Did you run DeepCreamPy's code yourself?

**Desktop (please complete the following information):**
 - Supports AVX?

**Additional context**
![Capture](https://user-images.githubusercontent.com/50161270/57004966-cd502880-6ba1-11e9-834f-d89a6b7fb23b.JPG)

**Comment by ccppoo** [comment]
unless you edited code, go to ../DeepCreamyPy-master/models and check if there's file name "model.h5"

**Comment by Flyersfan976** [comment]
How do you do that i have tried an it wont work i am only using the binary given when you download the program

**Comment by ccppoo** [comment]
@Flyersfan976 
What kind of release version did you downloaded?
![image](https://user-images.githubusercontent.com/46418312/57005775-c06d1c80-6c15-11e9-8123-db0718f5255e.png)
and those issue templates are not just decoration, you didn't filled even one of those

**Comment by Flyersfan976** [comment]
The newest sse and the computer is a hp omen 15 with i7 8th gen i also
downloaded the model file.

**Comment by ccppoo** [comment]
@Flyersfan976 
I just downloaded release version and it works and model.h5 was included in original zip file.
Why don't you just download again?
There's nothing more I could help and make sure you didn't changed directories or file names

**Comment by Kadantte** [comment]
@Flyersfan976 try to run DCP from source code check this #115

**Comment by Flyersfan976** [comment]
I re-downloaded it and ran the binary from my desktop where i exported it to  and it opens the program then says using tensor flow backend then it closes after it tries to start, i can not post the message since it closes the program when it appears

**Comment by Flyersfan976** [comment]
This is the message when i use the binary
![Capture II](https://user-images.githubusercontent.com/50161270/57055191-bc69ea80-6c67-11e9-9abb-13d4ba56d3be.JPG)

**Comment by ccppoo** [comment]
[OSError : cannot identify image file] could be raised in various ways, as you could find in google,
check this link
https://github.com/python-pillow/Pillow/issues/3287

your image could be malformed in some way or Try 'run as administrator'

for someone who search line of the code
Code of the latest release version
https://github.com/deeppomf/DeepCreamPy/blob/02490c22186b3e225c5866aa98ad7e07986cc16f/decensor.py#L51

line 2657 in PIL/images
https://github.com/python-pillow/Pillow/blob/c47792caeb9d24cfc6e9b97b039ba0db94d0f0c3/src/PIL/Image.py#L2657
