### ISSUE TITLE
Suggestion: Allow for multiple "runs" of an image to clean heavily-censored jaggedness

### ISSUE THREAD

**Issue by DarkPulse** [deeppomf/DeepCreamPy#141]
Depending on how blocky/pixelated/jagged a mosaic censor is, occasionally, the output of DeepCreamPy can also be similarly blocky/pixelated/jagged, revealing its nature as an algorithm.

However, you can mitigate the issue somewhat - the solution is to basically use the output of initial runs (as the "originals") to smooth and refine later runs of the same image. Doing this progressively smoothens out the decensor, and in turn, makes it look more like a natural part of the image as opposed to something that got decensored by DeepCreamPy.

There is a finite limit to this "artificial smoothing" of course, since eventually you will oversmooth it - 2-3 runs seems about optimal for a heavily-censored image. Of course, maybe better still would be with it being able to deal with heavily pixelated censors better in the first place, especially since oversmoothing causes other notable problems (mainly in the immediate pixels immediately surrounding the censored area).

The image set I'm trying this with has actually some fairly strong censorship - generally speaking, it's censored into 8x8 pixel squares, almost destroying the resolution (source image is 1600x1200) and details except in a rather vague sense, though the author saw fit to at least define edges to a somewhat looser extent (they still fit the overall "grid" pattern, but aren't perfect 8x8 squares). Given the heavy-handedness of the censoring, DeepCreamPy actually does a pretty admirable job, but this is definitely worse than many foes it will face, and it's visibly "different enough" from the rest of the image that the results aren't really acceptable for production-level use. DeepCreamPy certainly doesn't get much resolution data to go off of.

If need be, I can send some sample images (via private means, of course) to better train it on.

**Comment by ccppoo** [comment]
It sound like DCP needs a reconstruction, if this happen and a new smoothing method

**Comment by DarkPulse** [comment]
Well, again, it could well be because of the "toughness" of the censor.

An example (using the mermaid) would look something like this:

![image](https://user-images.githubusercontent.com/5454684/57347296-c7b58e00-711f-11e9-9127-f63a8cfafbe0.png)

Pretty rough stuff to try to recover image data from, and no way are you going to get the edges good without some really clever work.

I don't know what sort of training data @deeppomf has been using to train the models with, but my guess is that part of it is due to mosaics being beta (at least, of the last public version of DCP) and part of it might be him not really having trained it up to really handle those yet - DCP seems to be more focused on recovering simple bar censor-type stuff compared to mosaics at this point in time.

**Comment by ccppoo** [comment]
hmm... I bet deeppomf has those in mind and there are plenty of projects handling what you commented above. 
Maybe refering from other projects be a solution, or making a branch and commiting would help.

Still looks like a feature that needs a lot of time.
Thanks for your comment

**Comment by DarkPulse** [comment]
That'd be good, as a lot of the material I deal with tends to have mosaic censors instead of simple bar censors, since most of what I deal with are CG set releases as opposed to manga (where the bar censors dominate - but DCP can't handle black and white yet, either, which sucks as there's also a few manga I'd like to have decensored that *DO* use the bar censors.)

Thankfully the two types of things it can decensor are also the two things usually censored. I see some anal censoring once in awhile, but honestly can't remember the last time I saw a nipple censor.

Though I do also wonder if those are going to wind up on the table. For V2, I'd think they should be. DCPv1 is a good start for sure, but like I said, DCPv2 will justify money more the more it can do, and the less it looks like a machine algorithm did it.

All in all, I'll definitely put it to the test. If it does a good job, I'll probably even do some releases using it. Just need to hope it gets solid enough for my needs.
