### ISSUE TITLE
api-ms-win-crt-math-l1-1-0.dll is missing.

### ISSUE THREAD

**Issue by Hans3005** [deeppomf/DeepCreamPy#142]
I already have an image ready. But when I open the batch file I get an error saying

"api-ms-win-crt-math-l1-1-0.dll is missing'

So I downloaded it and extract it into the same location as DeepCreamPy. But I still keep getting the same message.

Is there a specific location on where I should put it?

**Comment by deeppomf** [comment]
Found this solution https://www.sts-tutorial.com/sites/downloadCenter.php?api-ms-win-crt-math-l1-1-0, but I warn you that I can't verify if the download is not a virus.

**Comment by Hans3005** [comment]
I've tried that exact link as well actually. It also didn't work. Looked up some more online and someone recommends to perform Windows Update after repairing my C++ Distributable 2015. Did that and I don't have this issue anymore. Instead I get another new issue, but I'll make a seperate post for that.
