### ISSUE TITLE
Tensorflow runtime error

### ISSUE THREAD

**Issue by Hans3005** [deeppomf/DeepCreamPy#146]
I followed Issue #26 solution up until step 3.

3. "pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl"

But I have error saying 
"tensorflow-1.10.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform"

New to Python, so anything I can do?

**Comment by Kadantte** [comment]
can u tell us what's your OS and what's ur python version, please?

**Comment by ccppoo** [comment]
first try uninstall Tensorflow and reinstall through pip command
Dont forget running command prompt by admin's authority(Windows)
