### ISSUE TITLE
Not working (Green parts are still on pic)

### ISSUE THREAD

**Issue by DIRETIDE** [deeppomf/DeepCreamPy#147]
Every time I'm trying to decensor smth, it just won't. Well, it does some color messing with green lines, but nothing more. Here's example:
![loadout (66](https://user-images.githubusercontent.com/51263046/58747832-594fbb80-8492-11e9-8ba9-f6c524d3bfae.png)

I'm not into coding all that much (Actually at all), so I have no idea what should I do and how to fix it.

**Comment by ccppoo** [comment]
If censored area is to large, it could show result like above

**Comment by DIRETIDE** [comment]
> If censored area is to large, it could show result like above
> Try https://www.fixmyphoto.ai/

I usually use squares to minimize the size of green areas, that was just an example. (Also link isn't working)

**Comment by DIRETIDE** [comment]
Mosaic do work, black bars don't. Dunno why, again.

**Comment by DIRETIDE** [comment]
> If censored area is to large, it could show result like above
> Try https://www.fixmyphoto.ai/

Tried smaller area, around usual size.
![loadout (66)](https://user-images.githubusercontent.com/51263046/58749246-72159c80-84a5-11e9-93f2-9cca2abfd2d9.png)

**Comment by ToxicFrazzles** [comment]
This issue could be caused by the pixels not being the exact correct colour. It seems to me that you are using a brush tool that softens the colour at the edges. Try using a box tool or changing a brush hardness setting.

**Comment by DIRETIDE** [comment]
> This issue could be caused by the pixels not being the exact correct colour. It seems to me that you are using a brush tool that softens the colour at the edges. Try using a box tool or changing a brush hardness setting.

That... actually was the case. Tried pencil tool and it worked. It didn't worked for squares bcs they were always at some degree, which made them be slightly transparent. I am a big idiot, thank you very much.
![loadout (66)](https://user-images.githubusercontent.com/51263046/58750049-dd17a100-84ae-11e9-94ea-b8d973e7d885.png)
