### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ARDEACT** [deeppomf/DeepCreamPy#148]
![image](https://user-images.githubusercontent.com/46211295/58756608-ea8e5480-84c9-11e9-941d-39aced047bc0.png)
Nothing came out of the output, why is that?

**Comment by aquamarim** [comment]
Old CPU use version with sse.

**Comment by Kadantte** [comment]
Please Check [Run Code Yourself on CPUs that don't support AVX instructions](https://github.com/deeppomf/DeepCreamPy/blob/master/docs/INSTALLATION.md#run-code-yourself-on-cpus-that-dont-support-avx-instructions).
