### ISSUE TITLE
After update demosaic filter produces yellow tint on output image

### ISSUE THREAD

**Issue by doratoa** [deeppomf/DeepCreamPy#149]
Using --is_mosaic=True and image with decensor area marked with green (0, 255, 0) results in yellowish tint and no other change in image pixels.

**To Reproduce**
1. Follow the guide and use color RGB(0, 255, 0)
2. `Run python decensor.py --is_mosaic=True`
3. Output image has yellow filter applied to working area (but nothing else appears to change)

At first I thought filter operates on different green color marker, but changing color results in `Found 0 censored regions in this image!` and it outputs original image.

**Expected behavior**
Worked fine prior to recent pull, I even had left  image  I played with before in input dirs and output changed completely.  Going to investigate which commit works.

**Installation method**
git clone

**Desktop (please complete the following information):**
 - OS: OpenSuSE 15.0 
 - Version: 7c21b666161f90a2cf5cee8a57cae3af5c4b04ee
 - Supports AVX: yes
- CPU: AMD Ryzen 7 1700 Eight-Core Processor

**Comment by doratoa** [comment]
Reverted back to 95e02e9 - no tint, demosaic changes images considerably (better or worse visually, but it does)
b9f6f68 - problem already present. Demo mermaid image is affected as well, so it's not issue with my pics.

**Comment by deeppomf** [comment]
Reproduced.
Time to squash some bugs.

**Comment by deeppomf** [comment]
@doratoa Turns out, the issue is the neural network model you have is out of date.
Download the newest one here https://drive.google.com/open?id=1Nzh2KAUO_rYPu2vDM_YP1EgbWtjI2hRX
