### ISSUE TITLE
Fail to execute the script decensor.py

### ISSUE THREAD

**Issue by Small-Ku** [deeppomf/DeepCreamPy#15]
Fail to execute the script decensor.py after found regions
IndexError: index 512 is out of bounds for axis 0 with size 512
[14196] Failed to execute script decensor
[1539745845871.zip](https://github.com/deeppomf/DeepCreamPy/files/2502453/1539745845871.zip)

**Comment by deeppomf** [comment]
Please delete that zip since it contains adult content.

Issue has been reproduced.

**Comment by deeppomf** [comment]
Error was caused by a variable incorrectly being reused.
