### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by smirgol** [deeppomf/DeepCreamPy#150]
Greetings!

I'm trying to get this application to run on Ubuntu 18.04, but get this error:

> Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "llvm_cpu.0"
Traceback (most recent call last):
  File "decensor.py", line 198, in <module>
    decensor = Decensor()
  File "decensor.py", line 22, in __init__
    self.load_model()
  File "decensor.py", line 31, in load_model
    self.model = PConvUnet()
  File "/mnt/volume/decensor/DeepCreamPy-1.3.0-beta/libs/pconv_hybrid_model.py", line 36, in __init__
    self.model = self.build_pconv_unet()
  File "/mnt/volume/decensor/DeepCreamPy-1.3.0-beta/libs/pconv_hybrid_model.py", line 77, in build_pconv_unet
    e_conv1, e_mask1 = encoder_layer(inputs_img, inputs_mask, 64, 7, bn=False)
  File "/mnt/volume/decensor/DeepCreamPy-1.3.0-beta/libs/pconv_hybrid_model.py", line 69, in encoder_layer
    conv, mask = PConv2D(filters, kernel_size, strides=2, padding='same')([img_in, mask_in])
  File "/mnt/volume/decensor/virtualenv/decensor/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/mnt/volume/decensor/DeepCreamPy-1.3.0-beta/libs/pconv_layer.py", line 64, in call
    normalization = K.repeat_elements(normalization, inputs[1].shape[2], axis=2)
IndexError: tuple index out of range

I'm using python 3.6 and installed all requirements (plus plaidml-keras, which was missing) to a virtualenv. I also downloaded and added the model data. 
When trying to run it on the default mermaid image, I get stuck with this error message. 

Any ideas what I might do wrong? :(
Thank you very much in advance!

**Comment by deeppomf** [comment]
plaidml-keras isn't required to run DeepCreamPy.
How did you install the requirements?

**Comment by ccppoo** [comment]
Windows working fine,
For someone who could solve this problem in linux/Ubuntu : 

**summary : problem at input ( need to trace back where it started ... )**

(call override in PConv2D's super class ; Conv2D)
*[ output = self.call(inputs, **kwargs) ](https://github.com/keras-team/keras/blob/cd3f27b5d2ccd843a2c98ee196f81217542e36c8/keras/engine/base_layer.py#L451)

(super class Conv2D from keras)
[Link](https://github.com/keras-team/keras/blob/91efaaa1d7486df71be30a54d82b907443d80bf1/keras/layers/convolutional.py#L361)
+at [here] (https://github.com/deeppomf/DeepCreamPy/blob/8996c4204c25052e0128de24fdf8f03d432b9a0d/libs/pconv_hybrid_model.py#L77) 
super().__init__(*args, **kwargs) (where error started)
is same to --> Conv2D(self, filters=64, kernel_size=7, strides =2, padding ='same')

add print method to check shape of keras.backend.repeat_elements at here([code](https://github.com/deeppomf/DeepCreamPy/blob/8996c4204c25052e0128de24fdf8f03d432b9a0d/libs/pconv_layer.py#L62)
like this 
`        normalization = K.mean(inputs[1], axis=[1,2], keepdims=True)
        print('normalization 1         : ', K.shape(normalization))
        normalization = K.repeat_elements(normalization, inputs[1].shape[1], axis=1)
        print('normalization 2         : ', K.shape(normalization))
        normalization = K.repeat_elements(normalization, inputs[1].shape[2], axis=2)
        print('normalization 3 (error) : ', K.shape(normalization))
        exit()
`
if it came with same result below, 
should look like this (used default mermaid image)
![image](https://user-images.githubusercontent.com/46418312/59321322-93c81c80-8d0c-11e9-9a07-28454285786e.png)

-----------------------------------------------------------------------------

I searched for methods that works on some OS, but I can't find it.
I'm not sure, but check your virtual machine's python package version.

**Comment by ccppoo** [comment]
Just looks like there's some override and it doesn't work with DCP
