### ISSUE TITLE
Discord bot port

### ISSUE THREAD

**Issue by magfag** [deeppomf/DeepCreamPy#151]
From what I know about discord bots, python or js is the preferred language so it wouldn't take much to port over. I know a lot of servers would instantly add this as a bot and would be extremely grateful.

**Comment by deeppomf** [comment]
A discord bot would be hard to implement because a drawing interface is needed to mark the censored areas and because the neural network file is pretty large.

**Comment by ccppoo** [comment]
@deeppomf 
Can I try one?

**Comment by mizz141** [comment]
Since this is an Open-Source project, you can fork it and work on a Discord bot...

**Comment by deeppomf** [comment]
@ccppoo There's nothing stopping you since DCPv1 is AGPL.
