### ISSUE TITLE
Doesn't work with tensorflow-rocm

### ISSUE THREAD

**Issue by LukyanovM** [deeppomf/DeepCreamPy#152]
Clean installation works fine got this after installation:

`pip3 install -r requirements.txt `
> Requirement already satisfied: tensorflow in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.13.1)
> Requirement already satisfied: absl-py in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.7.1)
> Requirement already satisfied: altgraph in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.16.1)
> Requirement already satisfied: astor in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.8.0)
> Requirement already satisfied: future in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.17.1)
> Requirement already satisfied: gast in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (0.2.2)
> Requirement already satisfied: grpcio in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.21.1)
> Requirement already satisfied: h5py in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.9.0)
> Requirement already satisfied: Keras in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2.2.4)
> Requirement already satisfied: Keras-Applications in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.0.8)
> Requirement already satisfied: Keras-Preprocessing in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.1.0)
> Requirement already satisfied: macholib in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.11)
> Requirement already satisfied: Markdown in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.1.1)
> Requirement already satisfied: numpy in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.16.4)
> Requirement already satisfied: pefile in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (2019.4.18)
> Requirement already satisfied: Pillow==5.3.0 in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (5.3.0)
> Requirement already satisfied: protobuf in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (3.8.0)
> Requirement already satisfied: pywin32-ctypes in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (0.2.0)
> Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from -r requirements.txt (line 19)) (3.13)
> Requirement already satisfied: scipy in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (1.3.0)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from -r requirements.txt (line 21)) (1.12.0)
> Requirement already satisfied: tensorboard in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 22)) (1.13.1)
> Requirement already satisfied: termcolor in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 23)) (1.1.0)
> Requirement already satisfied: Werkzeug in /home/mike/.local/lib/python3.7/site-packages (from -r requirements.txt (line 24)) (0.15.4)
> Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.32.3)
> Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0 in /home/mike/.local/lib/python3.7/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.13.0)
> Requirement already satisfied: setuptools>=36 in /usr/lib/python3/dist-packages (from Markdown->-r requirements.txt (line 13)) (40.8.0)
> Requirement already satisfied: mock>=2.0.0 in /home/mike/.local/lib/python3.7/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow->-r requirements.txt (line 1)) (3.0.5)

My hardware specs:
`grep -m1 "model name" /proc/cpuinfo && sudo lspci -d '::0300'`
> model name      : Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
> 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev c7)

So, I've installed ROCM stack and then upgraded my tensorflow with:
` pip3 install --user tensorflow-rocm --upgrade`
Decensor script still works:
`python3 decensor.py`

> Using TensorFlow backend.
> WARNING:tensorflow:From /home/mike/.local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> 2019-06-16 17:49:50.276113: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2019-06-16 17:49:50.327032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1531] Found device 0 with properties: 
> name: Ellesmere [Radeon RX 470/480/570/570X/580/580X]
> AMDGPU ISA: gfx803
> memoryClockRate (GHz) 1.29
> pciBusID 0000:01:00.0
> Total memory: 4.00GiB
> Free memory: 3.75GiB
> 2019-06-16 17:49:50.327073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1642] Adding visible gpu devices: 0
> 2019-06-16 17:49:50.327089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-06-16 17:49:50.327095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1059]      0 
> 2019-06-16 17:49:50.327109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1072] 0:   N 
> 2019-06-16 17:49:50.327152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3540 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:01:00.0)
> Decensoring the image ./decensor_input/mermaid_censored.png
> Found 17 censored regions in this image!
> 2019-06-16 17:50:04.245093: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
> 2019-06-16 17:50:04.248662: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
> 2019-06-16 17:50:04.289627: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
> 2019-06-16 17:50:04.293118: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
> 1 out of 17 regions decensored.
> 2 out of 17 regions decensored.
> 3 out of 17 regions decensored.
> 4 out of 17 regions decensored.
> 5 out of 17 regions decensored.
> 6 out of 17 regions decensored.
> 7 out of 17 regions decensored.
> 8 out of 17 regions decensored.
> 9 out of 17 regions decensored.
> 10 out of 17 regions decensored.
> 11 out of 17 regions decensored.
> 12 out of 17 regions decensored.
> 13 out of 17 regions decensored.
> 14 out of 17 regions decensored.
> 15 out of 17 regions decensored.
> 16 out of 17 regions decensored.
> 17 out of 17 regions decensored.
> Decensored image saved to ./decensor_output/mermaid_censored.png!
> Press anything to end

But the output image
![mermaid_censored_rocm](https://user-images.githubusercontent.com/43216037/59566213-9789d500-9065-11e9-923d-bce000332ee0.png)
 has blue marks, does someone get this script wotking on GPU?

**Comment by ccppoo** [comment]
If there a difference between TF-rocm and TF or some overrides, it could be a problem.
Same as this problem https://github.com/deeppomf/DeepCreamPy/issues/150
try re-install with original TF and remove rocm

**Comment by LukyanovM** [comment]
Of course there is difference between them. On vanilla TF standard synthetic test gives:
`python3 tf_cnn_benchmarks.py --device=cpu --data_format=NHWC --batch_size=32  --model=resnet50`

> total images/sec: 2.18

While the ROCM TF with the same test gives:
`python3 tf_cnn_benchmarks.py --num_gpus=1 --data_format=NHWC --batch_size=32  --model=resnet50`

> total images/sec: 76.57

I think performance boost over 30x is worth to consider TF-ROCM. At https://github.com/deeppomf/DeepCreamPy/issues/150 TS tries to run DCP on PlaidML. I'm noob in ML, but it requires code editing to port DCP from TF to PlaidML. On other side I'm trying to add low level hardware support for existing framework TF+Keras while code is staying the same.

**Comment by ccppoo** [comment]
Should find out what make those difference.

**Comment by deeppomf** [comment]
@LukyanovM DCP should be useable on as many devices as possible.
Although the performance boost would be great, ROCM doesn't support Windows.
