### ISSUE TITLE
Option to disable "Press anything to end..."

### ISSUE THREAD

**Issue by qT2DyV** [deeppomf/DeepCreamPy#155]
**DO NOT POST ADULT CONTENT**

**Is your feature request related to a problem? Please describe.**
Ever since the introduction of the "Press anything to end..." prompt, deepcreampy has been unable to run automatically inside of a script without human intervention

**Describe the solution you'd like**
A command line option such as "--autoclose" or something that would exit the program automatically instead

**Comment by ccppoo** [comment]
Sorry if you felt inconvenience
That was add to see the log in termial while running DCP. someone asked for it

I'll check it soon

**Comment by qT2DyV** [comment]
Yeah its helpful for windows users that don't want the cmd window disappearing at the end of the program but when i run DCP in the terminal i want it to exit normally. How it works now should be the default which is why I've asked for an option that disables it
