### ISSUE TITLE
Want white bar

### ISSUE THREAD

**Issue by godjacky2** [deeppomf/DeepCreamPy#162]
Want white bar decen

**Comment by styler00dollar** [comment]
It already can white bar decensor.

**Comment by ccppoo** [comment]
you can set mask color to 255,255,255 read "read me"

**Comment by godjacky2** [comment]
> you can set mask color to 255,255,255 read "read me"

how to set? 
I just used .exe version

**Comment by ccppoo** [comment]
in that case, I'll make a PR at Thursday. If it's a emergency, try running binary.

**Comment by godjacky2** [comment]
I already have python if I want to make PR. How can I do it?

> in that case, I'll try to make a PR at Thursday. If it's a emergency, try running binary.
> 
> edit: Well... making GUI (not painting) this time will be good for monetization

I already have python if I want to make PR. How can I do it?
