### ISSUE TITLE
I get this error everytime i try the mosaic

### ISSUE THREAD

**Issue by Axodique** [deeppomf/DeepCreamPy#164]
![ooo](https://user-images.githubusercontent.com/49350272/63201803-12cc2f00-c087-11e9-882f-a6faacce339a.PNG)
sorry it's in french but it means "windows couldn't find 'decensor.exe' make sure the name is correct then try again

**Comment by ccppoo** [comment]
this happens because of window's anti virus. Search google like "Window delete program without asking". It means window is thinking decensor.exe as a un-safe stuff.

**Comment by Axodique** [comment]
I fixed it by modifying the code of the .bat as it was somehow going to system32

**Comment by ccppoo** [comment]
if it works, make a PR!
