### ISSUE TITLE
Error message while decensoring mosaic

### ISSUE THREAD

**Issue by Lucretious** [deeppomf/DeepCreamPy#165]
Hi,

I tried the new 2.0 Beta. I tried decensoring some mosaic grayscale pictures, that, as far as I can say, had been correctly painted (color pallet changed to 8bit per chanel, color: 0,255,0). The strange thing is, the first image was decensored - and the quality is amazing!
But the other images won't work, with this error message:

Cannot find value of shape (1, 256, 256) for Tensor 'Placeholder:0', which has shape '(1, 256, 256, 3)
[14244] Failed to execute script decensor 

I tried the same with the old version 1.3, which also got me the same results. The first image works, the later not. But I am not able to catch the error message there.

I work with the binaries on a Windows 10, 64 Bit machine, which is up to date. My CPU is a Ryzen 2600x, which should support AVX1/2, and I have 16GB RAM. 
I already used your 1.3 a few times, and have successfully decensored mosaic and standard censors in the past, so I think my general workflow and colouring should be okay.

Does anybody has any advice, what could be the problem?

**Comment by ccppoo** [comment]
If you have full message of error from console log, can you post it? Image if possible. It would take some time

**Comment by Lucretious** [comment]
How so l Access the console log? I just took a screen capture. I can post this, but I am away from home, now, in about 4 hours or so. And I gladly add that console log, if you tell me how to get it.

**Comment by Lucretious** [comment]
A screenshot just before the program  closes:

https://imgur.com/RP9SlGq

**Comment by Lucretious** [comment]
Hi again,

I know, why it wouldn´t work. The original uncolored files must have the same color-range as the colored to-decensor files. In my example the original was grayscale, while I had to change the input files to 8 Bit per channel. This mismatch caused the error. Thus, this issue is closed.
Thanks again for this great software.
