### ISSUE TITLE
Window is not responding during decensoring

### ISSUE THREAD

**Issue by Arko109** [deeppomf/DeepCreamPy#173]
**Describe the bug**
After the starting the decensoring process, the window stops responding, because of that the user cannot see the log messages.

**To Reproduce**
1. Launch the exe
2. Click "Decensor Your Images"

**Expected behavior**
The window should stay responsive so that the user can see the logs

**Installation method**
Executable from release v2.2.0-alpha win64

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1903
 - Supports AVX? Yes

**Comment by ccppoo** [comment]
its happening because the decensoring and gui is working on a same thread (should be seperated)
going to be fixed soon
if you know how to run by python code, clone mine, latest PR

**Comment by deeppomf** [comment]
@Arko109 Are you still experiencing the not responding for v2.2.0-beta?

**Comment by Arko109** [comment]
@deeppomf well yes, but it's mostly gone now and occurs only for a brief moment. I'm closing this issue.
