### ISSUE TITLE
Tensorflow error

### ISSUE THREAD

**Issue by mishailovich** [deeppomf/DeepCreamPy#175]
When i am trying to install tensorflow i see this:
`tensorflow-1.10.0-cp36-cp36m-win32.whl is not a supported wheel on this platform.`
same with amd64 package
`tensorflow-1.10.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.`

I am using elementary os 5.0
My CPU Intel core 2 duo, i think it does not support AVX.
What am i doing wrong?

**Comment by mishailovich** [comment]
btw lol, I'm from Russia so I can make mistakes in sentences

**Comment by ccppoo** [comment]
as it says,tensorflow doesn't supports your platform (OS)
DeepCreamPy can't help you about this
you should ask Tensorflow about this issue

**Comment by mishailovich** [comment]
> as it says,tensorflow doesn't supports your platform (OS)
> DeepCreamPy can't help you about this
> you should ask Tensorflow about this issue

Ok. Anyway thanx. I will try DeepCreamPy on my main pc, with windows and intel core i7

**Comment by ccppoo** [comment]
@mishailovich good luck

**Comment by Kadantte** [comment]
The TensorFlow that is been provided with DCP is for windows platforms so you need to install TensorFlow for Linux try one of this:
https://github.com/yaroslavvb/tensorflow-community-wheels/issues/103
https://github.com/davidenunes/tensorflow-wheels

**Comment by mishailovich** [comment]
So I ran the program:
`python3 decensor.py`
Now it started without errors. The following message appeared in the terminal:
![image](https://user-images.githubusercontent.com/41520056/67975890-08511880-fc26-11e9-8fa2-240bc16d5ca1.png)
The message hasn't changed in twenty minutes. Is that how it should be?

**Comment by deeppomf** [comment]
@mishailovich
decensor.py was broken today since I am ending support for the CLI temporarily.
Use main.py.

**Comment by mishailovich** [comment]
@deeppomf 
I tried running through main.py, the same result.  The program displays a message, and then remains inactive. There is no CPU load in the process manager.

**Comment by ccppoo** [comment]
@mishailovich 
can you copy and paste the message?
Did you installed requirements? ( python packages  : that could be installed through "pip" or "conda")

**Comment by mishailovich** [comment]
![image](https://user-images.githubusercontent.com/41520056/68012517-56543380-fc9b-11e9-9469-33eb827cf026.png)

> can you copy and paste the message?
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/mishailovic/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mishailovic/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mishailovic/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mishailovic/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mishailovic/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mishailovic/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

> Did you installed requirements?
Yeah, through pip3, except tensorflow, I set it manually

**Comment by ccppoo** [comment]
@mishailovich 
first of all, those messages aren't really serious problems, it's just one of announcing,
I also see those message when I run it.
but if there's no action after showing those message, I could say it's not problem of TensorFlow nor DeepCreamPy. 
It could be taking time loading model( file size about 320MB) , in my case it takes about 40 seconds, monitor your Memory (REM) if it spikes up about 1GB (based on my PC).
If nothing happens I have no clue what your problem is.

**Comment by mishailovich** [comment]
Thank you so much for your answers! I will continue to try.
