### ISSUE TITLE
High Memory Usage with 2.X versions. 

### ISSUE THREAD

**Issue by Colt-Zero** [deeppomf/DeepCreamPy#176]
**Describe the bug**
When I try to use the 2.0 and 2.2 builds of DeepCreamPy it just hangs at the beginning and builds up memory usage, and I don't feel safe with it going up to like 5 gigs, so I always end the the task when it reaches that point.

I don't know if it would actually work were I to let it keep going, but my previous experience was with the 1.3 build. And that version does not take up nearly as much, so I'm leaning on this being an actual bug. And the 1.3 build is able to handle the same images just fine.

**To Reproduce**
1. Provide images in the input folders.
2. Run the program after having the requirements properly installed
3. Gets to the point where it's loading tensorflow
4. Does nothing and builds up more and more memory usage.

**Expected behavior**
I don't know, just for the program to not use up this much memory. I haven't seen any warnings for this program taking up this much, 

**Installation method**
I tried both binary and from source for 2.2. I've only tried from binary for 2.0

**Desktop (please complete the following information):**
 - OS: Windows
 - 10x64
 - Supports AVX? Yes

**Additional context**
I only have 8 gigabytes of free ram on my computer, and I am using a fairly old NVidia GTX 650 GPU. So I'm honestly unsure at this point whether it's an actual bug or if it's just my hardware.

**Comment by ccppoo** [comment]
so can you tell us again after tryijg 2.2?

**Comment by Colt-Zero** [comment]
> so can you tell us again after tryijg 2.2?

I did? I tried 2.2 before 2.0. 
I switched to 2.0 after seeing the 2.2 version give a message that it couldn't
use Cuda since I only have support up to Cuda compute 3.0 and it wanted Cuda compute 3.5.
In order to address that, I had to downgrade tensorflow from 1.14 to 1.12.

**Comment by ccppoo** [comment]
yeah I think all other users experiencing freeze and not working is due to memory

**Comment by deeppomf** [comment]
Adding less memory hungry neural networks to my to-do list, but other tasks will come first.
