### ISSUE TITLE
Fail to run main.py

### ISSUE THREAD

**Issue by qqvdk2** [deeppomf/DeepCreamPy#179]
**Describe the bug**
when I run
**python main.py**

then

Error when importing libraries:  Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Some Python libraries are missing. You can install all required libraries by running in the command line 'pip install -r requirements.txt' 

**Installation method**
Did you install DeepCreamPy with the binary? No
Did you run DeepCreamPy's code yourself? DeepCreamPy-2.2.0-beta

**Desktop (please complete the following information):**
 - OS: Windows
 - Version : 8.1 64bit
 - Supports AVX? No

**Additional context**
I have installed all requirements.

**Comment by ccppoo** [comment]
It looks like tensorflow install error, 
try follow https://github.com/tensorflow/tensorflow/issues/23683#issuecomment-510718458  : 
reinstalling tensorflow by anaconda

in your terminal or command prompt ... 
1. pip uninstall -y tensorflow
2. conda install tensorflow=1.14

**Comment by qqvdk2** [comment]
I tried, but when I ran main.py again, and

Error when importing libraries:  No module named 'tensorflow.contrib'
Some Python libraries are missing. You can install all required libraries by running in the command line 'pip install -r requirements.txt'

when I checked the requirements, it reinstalled  tensorflow-1.14.0, but when I ran the code, the old bug above reappeared.

**Comment by ccppoo** [comment]
most of the solution for this error I saw from Tensorflow repository was re-installing python and other gpu cuda driver (using gpu case)

https://github.com/tensorflow/tensorflow/issues/22512
https://github.com/tensorflow/tensorflow/issues/22794

These were linked from tensorflow document, so I think this will help you
