### ISSUE TITLE
Parts marked with green aren't detected if they are on the bottom right of the image

### ISSUE THREAD

**Issue by Homuranana** [deeppomf/DeepCreamPy#18]
I noticed when I try to decensor certain images, it works well except when the marked area is on the bottom right. That part isn't decensored and retains its green. A workaround is flipping the image horizontally and flipping it again when the image is finally decensored.

**Comment by deepWhomst** [comment]
Do you have a test case that can be used to replicate the issue? That would make debugging faster.

**Comment by deeppomf** [comment]
Issue has been replicated.
