### ISSUE TITLE
Tensorflow.js Support

### ISSUE THREAD

**Issue by stefnotch** [deeppomf/DeepCreamPy#182]
**DO NOT POST ADULT CONTENT**

**Is your feature request related to a problem? Please describe.**
I wanted to take a stab at running this in the browser. To do so, Tensorflow.js would have to be used. Is there currently anything preventing this? 

**Describe the solution you'd like**
An answer regarding whether the usage of Tensorflow.js is possible and why.

**Describe alternatives you've considered**
Simply run this using Python

**Additional context**
A relevant comment says
> The model can't be loaded with tensorflow.js because custom Keras layers aren't supported
> -- https://github.com/deeppomf/DeepCreamPy/issues/48#issuecomment-435580785 

However, this seems to have changed.
https://github.com/tensorflow/tfjs-examples/pull/61

**Comment by deeppomf** [comment]
I am not sure about Tensorflow.js support.
What would the benefits of DeepCreamPy in the browser be?

**Comment by stefnotch** [comment]
The main use case would probably be the ability to turn this into a browser plugin that kicks in automatically on certain websites. Which would potentially make this far easier to use.

Another one would be having a cross platform browser based GUI (aka website) instead of the current approach.

**Comment by deeppomf** [comment]
Improving decensoring is the main priority so I don't foresee TF.js support.
