### ISSUE TITLE
link to Install instructions on github produce a 404 error

### ISSUE THREAD

**Issue by CGanimated1227** [deeppomf/DeepCreamPy#193]
I cannot effectively use this program because I am missing the instructions because the link to the Install instructions on github produce a 404 error. Could they be added as a .txt file to future versions or at least can you please fix the link?

**Comment by RuhtraX** [comment]
You mean this file? https://github.com/deeppomf/DeepCreamPy/blob/master/docs/INSTALLATION.md

The link in the README is working fine

**Comment by Kadantte** [comment]
@CGanimated1227  All links are working fine, please put the link here so we can try and fix it... I looked into all the links and everything is okay. Just put the link here and we're gonna fix it for ya.

**Comment by CGanimated1227** [comment]
@Kadantte This is the broken link:https://github.com/deeppomf/DeepCreamPy/blob/master/INSTALLATION_BINARY.md
@RuhtraX Thank you, I will try following the instructions there. You put the dependencies in the DeepCreamyPy folder, right? It doesn't exactly tell you were to put these things.

**Comment by RuhtraX** [comment]
@CGanimated1227 
The dependencies must be installed on your computer, as it says in the installation instructions you can run `pip install -r requirements.txt` (considering you already have python and pip installed), or if you're on windows you can download and use the prebuilt binary.

**Comment by CGanimated1227** [comment]
@Kadantte Thank you very much.
@RuhtraX I'm on a windows 8.1 laptop, so all I need is one of the releases from the links in the install instructions, right? I know this is becoming another issue, but no output is being made when I run the program, no matter wich version I use. Could this have to do with processing power?

**Comment by Kadantte** [comment]
@CGanimated1227 
is your CPU supports AVX? if not you need to run the code yourself so look here: [INSTALLATION.md](https://github.com/deeppomf/DeepCreamPy/blob/master/docs/INSTALLATION.md)

**Comment by CGanimated1227** [comment]
I tried following the directions to the T and I do not understand why the "pip" commands do not work. I installed the right version of python, I have the listed dependencies, but they won't install through command prompt for some reason. I'm a total noob to coding like this and I'm using 1.3.0 because 2.2.0 crashes my computer and I have to hard reset it to get it to work again.

**Comment by CGanimated1227** [comment]
Update on my situation: I used the latest version of DeepCreamyPy on a new computer and it works. Thanks for you help.
