### ISSUE TITLE
DeepCreamPy stuck and doesn't load

### ISSUE THREAD

**Issue by GGPeridot** [deeppomf/DeepCreamPy#199]
When i try to run the decensors it just doesn't work it is completly blank.

**Expected behavior**
It is supposed to decensors the image but it just don't want to.

**Screenshots**
![image](https://user-images.githubusercontent.com/57356716/74935571-6e56eb00-5423-11ea-8c5d-02b127bc9762.png)

**Installation method**
Did you install DeepCreamPy with the binary?
Did you run DeepCreamPy's code yourself?

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Version Ultimate
 - Supports AVW: no

**Additional context**

**Comment by Kadantte** [comment]
If your CPU doesn't support AVX instructions you need to run the code your self.
For more information about how you can run the code by your self please see this [documentation](https://github.com/deeppomf/DeepCreamPy/blob/master/docs/INSTALLATION.md).

**Comment by GGPeridot** [comment]
![image](https://user-images.githubusercontent.com/57356716/75103526-85b9f200-5636-11ea-86e0-9cc37107c27b.png)
im still stuck here

**Comment by Kadantte** [comment]
Here's what you need to do first:
```shell
$ git clone https://github.com/deeppomf/DeepCreamPy.git
$ cd DeepCreamPy
$ pip install -r requirements.txt
```
If your CPU doesn't support AVX you should try this one:
1-Start from a clean Python 3.6.7 install
2- Download TensorFlow for [SSE2](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.10.0/py36/CPU/sse2), After yoy download it copy paste into DCP root folder.
3- create a text file then name it `requirements.txt` after you name it, copy paste the text below but make sure to re-name `tensorflow==1.15.0` to the same wheel you downnloaded from SSE2 version it should looks like this `tensorflow-1.15.0-cp37-cp37m-win_amd64.whl`
```
absl-py==0.7.1
astor==0.8.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.22.0
h5py==2.9.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.17.0
opencv-python==4.1.0.25
Pillow==6.2.0
protobuf==3.9.1
PySide2==5.13.0
scipy==1.3.0
shiboken2==5.13.0
six==1.12.0
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow==1.15.0
termcolor==1.1.0
Werkzeug==0.15.5
wrapt==1.11.2
```
4- open your terminal do as below.
```shell
$ git clone https://github.com/deeppomf/DeepCreamPy.git
$ cd DeepCreamPy
$ pip install -r requirements.txt
```
