### ISSUE TITLE
Slowdown running decensor.py on OS X

### ISSUE THREAD

**Issue by throwawaygate** [deeppomf/DeepCreamPy#22]
Ran code on an anaconda environment on Mac 10.14. 2.6 ghz intel i5, 8 GB ram, Intel Iris 1536 MB integrated gpu. Test image (mermaid) took roughly ~20 mins running with no other programs open. Is this normal for these specs? I ran the binary on a windows 10 VM  running on virtualbox with 2 cpus and 4 gb ram on the same computer and it seemed to go through the regions faster.

**Comment by deepWhomst** [comment]
Try building tensorflow from source and see if that helps a little.
https://www.tensorflow.org/install/source#macos
Other than that, I have no idea why Tensorflow would be so slow on bare metal and so fast on a VM, other than the mac binary being horribly unoptimized.

**Comment by deeppomf** [comment]
Running slowly is strange, but I don't have a Mac to test on.
Maybe anaconda causes the slowdown? Have you tried uninstalling anaconda, installing Python 3.6, and installing the packages with pip?

**Comment by throwawaygate** [comment]
Found the issue. When I set up my conda environment, I installed some requirements then tried `pip install -r requirements.txt` which may have configured the dependencies incorrectly. Doing a fresh reinstall fixes the issue.
