### ISSUE TITLE
Adding debugging log or accuracy measure?

### ISSUE THREAD

**Issue by throwawaygate** [deeppomf/DeepCreamPy#23]
Is there anyway to provide more information to the user through the console output on how much of it succeeded? Some kind of accuracy or percentage of successful decensoring metric?

**Comment by deepWhomst** [comment]
Very unlikely. If you have a better algorithm that can decide how good an attempt was, you could use that model to train the NN to get better at doing the decensoring in the first place. A domain-specific model for evaluating the painting over censor holes could be created with enough effort, but at the end of the day a human is going to have to evaluate the image and say "yes, this is good" or "no, the NN really flopped on this one". What purpose did you have in mind for the evaluation? If it's critical, have you considered using MechanicalTurk for evaluation?

**Comment by deeppomf** [comment]
It's not possible to get such a metric from this project's neural network.
