### ISSUE TITLE
decensor_mosaic Shortcut File Path Error

### ISSUE THREAD

**Issue by wave-dash** [deeppomf/DeepCreamPy#29]
In the Windows binary version 1.2.1, the decensor_mosaic shortcut file has this as its "start in" field:

C:\Users\larry\Desktop\DeepCreamPy_1.0.0-beta_win64

I believe that causes this error when running the shortcut:

OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Manually changing the "start in" field to the folder path (C:\Users\Name\Downloads\DeepCreamPy_1.2.1-beta_win64) fixed that OSError.

**Comment by deeppomf** [comment]
Once the UI is finished, I can get rid of this ugly mosaic shortcut hack.

**Comment by deeppomf** [comment]
@Aaron2550 Going to replace the shortcut with a bat .script.

**Comment by Aaron2550** [comment]
> @Aaron2550 Going to replace the shortcut with a bat .script.

Thanks!
