### ISSUE TITLE
Please show useful examples of real hentai.

### ISSUE THREAD

**Issue by yosun** [deeppomf/DeepCreamPy#32]
Is the readme example deeply censored? Please show useful use cases.

**Comment by deeppomf** [comment]
Any reasonable person would know posting hentai would be against [Github community guideline](https://help.github.com/articles/github-community-guidelines/).

**Comment by yosun** [comment]
> Sexually obscene content - Basically, don't post pornography. This does not mean that all nudity or sexual content is prohibited. **We recognize that sexuality is a part of life and non-pornographic sexual content may be a part of your project, or may be presented for educational or artistic purposes.** If you have any questions or concerns about something you want to post, feel free to reach out and ask beforehand.

Seems fine in context of educational purposes to demonstrate the best case examples of your particular implementation.
