### ISSUE TITLE
i 

### ISSUE THREAD

**Issue by Lincolnator42069** [deeppomf/DeepCreamPy#34]
[Images redacted because Github Community Guidelines prohibits adult content]

this is the before and after for this image
i turned anti aliasing off, and i am absolutely sure i colored it correctly

**Comment by deeppomf** [comment]
Posting hentai is against [Github community guidelines](https://help.github.com/articles/github-community-guidelines/).

There are a few green pixels that aren't (0,255,0)

If you're using GIMP, the problem might be from not turning anti-aliasing off when using selection tools.
