### ISSUE TITLE
Decensor_mosaic not working.

### ISSUE THREAD

**Issue by Shinaitsa** [deeppomf/DeepCreamPy#37]
^ it simply doesn't respond to double-clicks. No error, no processes, no results, nothing. Trying to use the latest version (the 3 days ago one).

**Comment by Shinaitsa** [comment]
Also, checked just to make sure, my Win is 64-bit.

**Comment by deeppomf** [comment]
Have you tried https://github.com/deeppomf/DeepCreamPy/issues/29?

**Comment by Shinaitsa** [comment]
Oh, hm... I'm unable to change it, it's greyed out.

**Comment by DennisWeyrauch** [comment]
Can't you just tell us what command argument to use for it?

**Comment by deepWhomst** [comment]
Running the application with semi-standard (for windows) help "-h" arg causes it to print all of its flags and options. In this case, the arg you're looking for is the mosaic flag? It's --is_mosaic {true/false}

**Comment by deeppomf** [comment]
Should be fixed in newest update.
