### ISSUE TITLE
Green color issue

### ISSUE THREAD

**Issue by sanscriptum** [deeppomf/DeepCreamPy#38]
The soft seems to be a bit overzealous when it comes to green color, for instance I was trying to decensor a picture with a character dressed in green, and despite not being strictly green (0,255,0), the soft thought it was marked for decensor and then proceeded working on nearly 500 areas.
Not sure if it was just an issue with this particular picture or in general though.

**Comment by EIREXE** [comment]
I'm pretty sure it only hits 0,255,0 pixels

**Comment by duncannah** [comment]
Could be the color space changing when you save the pictures, so it shifts those colors to 0,255,0

**Comment by deepWhomst** [comment]
If you have an issue with the wrong colour being masked out, consider using the flags to change which colour the application is looking for.

**Comment by deeppomf** [comment]
If you're using Photoshop, make sure you are exporting images to sRGB format.

**Comment by sanscriptum** [comment]
The picture in question went through waifu2x beforehand and was upscaled up to 4k resolution. After editing it in photoshop, I saved it just like I did with all other images with the same settings. Yet picrelated was occurring. FYI, I used some 4k upscaled pictures before and they worked fine, but they didn't feature any green though.

![image](https://user-images.githubusercontent.com/3057589/47773857-71910980-dcfc-11e8-95dc-2ba4efc1eb7f.png)

I can confirm that (0, 255, 0) is pretty much required because when I tried to use a color with a slight deviation (something about 0, 255, 9), no detection has occurred.
Curios, I allowed the soft to work on those ~500 areas it "detected". I'm not sure if I'm allowed to link the image or the result since they're nsfw.
Then I tried to pull the original non-upscaled picture from booru, edited it the same, saved the same, and it worked just fine. So it's hard to say what exactly was happening.

**Comment by sanscriptum** [comment]
Alright, I think I know what was happening there. @duncannah was right and the color did indeed shift somehow. So instead of having one single green line it had to work on literal pixels that still had correct color attached. The fact that character was wearing green didn't help and confused me a little.
