### ISSUE TITLE
AVX2 (need more help)

### ISSUE THREAD

**Issue by AmberrOsu** [deeppomf/DeepCreamPy#41]
So I tried to use this program and i got the AVX2 issue, I know it has already been addressed but since I don't have much knowledge in programming whatsoever, I can't even follow the other guides on running it myself at all, I was wondering if there's an easy way around this issue, if it helps, my CPU is an i5-7600k. 
![2018-10-31_00-43-48](https://user-images.githubusercontent.com/42164572/47759738-dcb0f080-dca8-11e8-9a56-5e41705c0bc3.png)

**Comment by Kadantte** [comment]
Look here #26

**Comment by AmberrOsu** [comment]
I probably did something wrong but this is what I got after downloading the file and entering the command.
![cmd_2018-10-31_03-49-43](https://user-images.githubusercontent.com/42164572/47765078-23f6ab80-dcc0-11e8-9436-622c6a01b20e.png)

**Comment by pshah123** [comment]
You don't actually need to compile with AVX2, you can ignore this along with SSE and the other optimizers.

Also, Windows does not come with Python, pip is a Python package manager. The easiest Python installation is going to be [Anaconda](https://www.anaconda.com/download/).

I do not advise running this repo without prior knowledge of Python/TF as you may run into errors with PATH and etc.

**Comment by AmberrOsu** [comment]
Yea, I won't be able to understand any of this lol, I'll just wait until it has a GUI for users or see if it works on a VM later.
Thanks for the attempted help though :)

**Comment by Kadantte** [comment]
You need to Add Python to ur PATH

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
> 
> 
> Yea, I won't be able to understand any of this lol, I'll just wait until it has a GUI for users or see if it works on a VM later.
> Thanks for the attempted help though :)

For this, you can download the "binary" version. Currently called DeepCreamPy_1.2.1-beta_win64. 
It comes with every prerequisite already stacked inside, you need no programming tools on your PC.

Place your image to decensor in the decensor_input, make sure it's saved in .png format (insisting: .jpg won't fly and cause the program to stop without doing anything), run decensor.exe, and it should do, you'll see the progression messages from there on.

As for the AVX2 message itself, it can be disregarded, it's an information of the kind "yeah, we could do that, but we won't, however that won't prevent us from doing our job", more like a useless side note.

**Comment by Aaron2550** [comment]
> I probably did something wrong but this is what I got after downloading the file and entering the command.
> Edit: Also the file says AMD, does it matter than my CPU is intel?
> ![cmd_2018-10-31_03-49-43](https://user-images.githubusercontent.com/42164572/47765078-23f6ab80-dcc0-11e8-9436-622c6a01b20e.png)

Uhm, just by the way, you cant use pip in cmd, use powershell see: [https://files.catbox.moe/45zl0c.png](url)

**Comment by Kadantte** [comment]
@Aaron2550 [https://github.com/deeppomf/DeepCreamPy/issues/41#issuecomment-434595389](url)

**Comment by Aaron2550** [comment]
> @Aaron2550 [https://github.com/deeppomf/DeepCreamPy/issues/41#issuecomment-434595389](url)

Sorry! I at some point could'nt get pip to work in cmd so i just assumed thats how its supposed to be
btw; your link doesnt work, _replace the "url" in (url) with the actual url_
![image](https://user-images.githubusercontent.com/24834067/47934899-f89ad900-ded8-11e8-889b-01ed8dbb9681.png)

**Comment by Kadantte** [comment]
> > @Aaron2550 [https://github.com/deeppomf/DeepCreamPy/issues/41#issuecomment-434595389](url)
> 
> Sorry! I at some point couldnt get pip to work in cmd so i just assumed thats how its supposed to be
> btw; your link doesnt work, _replace the "url" in (url) with the actual url_
> ![image](https://user-images.githubusercontent.com/24834067/47934899-f89ad900-ded8-11e8-889b-01ed8dbb9681.png)

I Edit it.

**Comment by akeno0605** [comment]
I'm having a similar issue with the AVX2 in my windows binary. I'm using python 3.6.7 64 bit. Have tried tensorflow 1.11.0\py36\CPU\avx2 but the warning still pops out.
![5](https://user-images.githubusercontent.com/44789614/48032274-f88f1900-e124-11e8-8964-4932146a4334.png)

**Comment by junh1024** [comment]
This warning can be disregarded as https://github.com/deeppomf/DeepCreamPy/issues/41#issuecomment-434639082 said.

**Comment by deeppomf** [comment]
@akeno0605 Did the decensoring work? If it did, don't worry about the warning.
