### ISSUE TITLE
Is it work on windows 10?

### ISSUE THREAD

**Issue by Vladsmesh1** [deeppomf/DeepCreamPy#47]
So, I download DeepCreamPy_1.2.1-beta_win64, unzip it to folder, take your mermaid_censored.png into decensor_input folder, doubleclick on decensor.exe and I see just this (screenshot),
![wa](https://user-images.githubusercontent.com/44685165/47881964-f5e8a700-de38-11e8-8273-588a6efa3777.png)
CPU begins to do something (I hear increasing speed of the fans) and cmd closes. I check some info in "issues", and install all Microsoft vusual's (2009-2017), nothing works. I tryed previous version of DeepCreamPy - same thing.
My cpu is i7 8700k by the way. Windows 10 64bit 1809.

UPD: It's just work 1 time after 3 hours of attempts. So, tell me please where I made a mistake. I change nothing, just click and click on .exe again and again.

And sorry for my bad english, I'm not from an English speaking country.

**Comment by FieryKitsune** [comment]
This program doesn't work on .jpg or .jpeg files. Use .png instead.

**Comment by Vladsmesh1** [comment]
> This program doesn't work on .jpg or .jpeg files. Use .png instead.

I use original mermaid_censored.png

By the way, I solved the problem. For some reason, original file was saved by google chrome as mermaid_censored.PNG (with big letters). I rename file as .png (with small letters) and it perfectly works!

By the way, Photoshop automatically saves files as .PNG, so, it is advisable to consider file format with a capital letter in the following updates :)

**Comment by deeppomf** [comment]
@Vladsmesh1 The fix is in the repo but not in the binary.
