### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by bulsar-38** [deeppomf/DeepCreamPy#49]
Well, I know it probably is a pretty dumb but how does it work ? like What have I to do x) ?

**Comment by deeppomf** [comment]
Did you read [this](https://github.com/deeppomf/DeepCreamPy/blob/master/USAGE.md)?

**Comment by bulsar-38** [comment]
No and thank you, I am looking toward it <3

**Comment by Kazamimi** [comment]
I will ask here.
**Is the binary all you need to run deepcreampy?** I'm given the impression that "Run Code Yourself" in Installation.md means compiling it yourself.

When I run the executable the terminal stays open for some time then quickly prints out text and closes immediately without doing anything. I took a screenshot of what I could. The directories in the log aren't mine.

![untitled](https://user-images.githubusercontent.com/24215345/47944750-f8e4a580-ded3-11e8-8817-b960da5a2c5a.png)

**Comment by Aaron2550** [comment]
> I will ask here.
> **Is the binary all you need to run deepcreampy?** I'm given the impression that "Run Code Yourself" in Installation.md means compiling it yourself.
> 
> When I run the executable the terminal stays open for some time then quickly prints out text and closes immediately without doing anything. I took a screenshot of what I could. The directories in the log aren't mine.
> 
> ![untitled](https://user-images.githubusercontent.com/24215345/47944750-f8e4a580-ded3-11e8-8817-b960da5a2c5a.png)

yep, you only need the .zip from releases, no dependencies or anything [https://github.com/deeppomf/DeepCreamPy/releases](https://github.com/deeppomf/DeepCreamPy/releases)

**Comment by bulsar-38** [comment]
It works perfectly thank you :D and good job
