### ISSUE TITLE
Sometimes some green spots do not get "fixed"

### ISSUE THREAD

**Issue by Aaron2550** [deeppomf/DeepCreamPy#51]
Maybe i did something wrong, but i assured AA is off and RGB values are 0 255 0
See here: 
![image](https://user-images.githubusercontent.com/24834067/47939500-cd6bb600-dee7-11e8-80e8-8bb00de3d967.png)

I fixed it by making a batch file which runs decensor.exe, then deletes the image(s) from input, moves the image(s) from output to input and runs decensor.exe again: 
[Decensor x2.zip](https://github.com/deeppomf/DeepCreamPy/files/2544055/Decensor.x2.zip)
(had to zip it because Github doesnt support upload of .bat's) put it next to the decensor.exe

Its not a beautiful solution, maybe this could be integrated somehow, would be even better if the issue would be fixed :P

Im really damn proud of my work right now ^^'

**Comment by deeppomf** [comment]
Did you edit the image in photoshop? If you did, did you export the image to the sRGB color mode?

**Comment by Aaron2550** [comment]
> Did you edit the image in photoshop? If you did, did you export the image to the sRGB color mode?

Paint.NET exported as png, i dont think you can set what color mode to export in? 
![image](https://user-images.githubusercontent.com/24834067/47951422-d056bd00-df60-11e8-8ca2-e421d3de1deb.png)

**Comment by deeppomf** [comment]
Could you post the censored image for me to test with?

**Comment by Aaron2550** [comment]
i might actually not have it anymore, let me check

**Comment by Aaron2550** [comment]
![test2](https://user-images.githubusercontent.com/24834067/47951761-82908380-df65-11e8-968d-088f24e5eb05.png)
![test2 2](https://user-images.githubusercontent.com/24834067/47951757-760c2b00-df65-11e8-88dc-d8ee5a3620f7.png)

**Comment by deeppomf** [comment]
This is a bug with the decensoring code. Looking into it.

**Comment by Aaron2550** [comment]
alright, thanks!

**Comment by Crazyrobot321** [comment]
May i ask what is this doujin is called?  😇

**Comment by Aaron2550** [comment]
> May i ask what is this doujin is called? 😇

this is

**Comment by Aaron2550** [comment]
oups, didnt want to close the issue, its [https://nhentai.net/g/250681/](url)

**Comment by deeppomf** [comment]
Fixed it as best as it can. Neural network takes in cropped images that are square which creates issues with censors that take up the entire page.
