### ISSUE TITLE
Failed to load native TensorFlow runtime

### ISSUE THREAD

**Issue by Yoshicrafter1531** [deeppomf/DeepCreamPy#54]
Umm help, If seems I'm losing something but I don't have no idea of what is TensorFlow Runtime neither installing it https://media.discordapp.net/attachments/404105966716583957/508291697726193665/unknown.png?width=804&height=452

**Comment by Aaron2550** [comment]
see https://github.com/deeppomf/DeepCreamPy/issues/26#issuecomment-434043166
