### ISSUE TITLE
I can't get the program to work

### ISSUE THREAD

**Issue by Morpny-kun** [deeppomf/DeepCreamPy#56]
I downloaded the program yesterday on a Linux system (Linux Mint 19 to be exact), even after following the instructions found in README.md to the best of my ability i.e installing all the modules and downloading model.h5, I couldn't get the program to work.
I got this error message:
![screenshot from 2018-11-04 09-08-52](https://user-images.githubusercontent.com/44739457/47959903-56cad780-e011-11e8-8de7-1812e5754c9d.png)

Traceback (most recent call last):
  File "decensor.py", line 8, in <module>
    from libs.pconv_hybrid_model import PConvUnet
ImportError: No module named libs.pconv_hybrid_model

I'm pretty much a novice at python so I can't figure out what the problem is, please help.

**Comment by Morpny-kun** [comment]
![screenshot from 2018-11-04 14-00-50](https://user-images.githubusercontent.com/44739457/47962149-2cd9db00-e03a-11e8-879f-a257a7e11f1f.png)
![screenshot from 2018-11-04 14-00-15](https://user-images.githubusercontent.com/44739457/47962152-3105f880-e03a-11e8-90d7-22b67e0c6b99.png)
 No, I don't think so.

**Comment by Morpny-kun** [comment]
> Did any of the files or folders get renamed? I don't have this problem on Ubuntu 16.04

**Comment by Morpny-kun** [comment]
> Did any of the files or folders get renamed? I don't have this problem on Ubuntu 16.04

![screenshot from 2018-11-04 14-00-50](https://user-images.githubusercontent.com/44739457/47962178-9659e980-e03a-11e8-8790-0e90b3f4a8a0.png)
![screenshot from 2018-11-04 14-00-15](https://user-images.githubusercontent.com/44739457/47962179-98bc4380-e03a-11e8-852a-72bfb8961c77.png)
No, I don't think so.

**Comment by deeppomf** [comment]
Did any of the files or folders get renamed? I don't have this problem on Ubuntu 16.04

**Comment by Morpny-kun** [comment]
> What version of Python are you using?
Umm... I have both 3.6 and 2.7 but I was using 2.7 to run the program.

**Comment by Kadantte** [comment]
@Morpny-kun DCP doesn't Supp 2.7 u need to run it with 3.6.

**Comment by Morpny-kun** [comment]
I installed all the modules for python3.6 and than ran the program using python3 but it still didn't work, this time I got this message:
![screenshot from 2018-11-09 18-53-02](https://user-images.githubusercontent.com/44739457/48266333-deb94300-e450-11e8-816a-68b63eae7180.png)
Sorry for such a late reply.

**Comment by Kadantte** [comment]
np, Okay... try to uninstall tensorflow and install it from here [](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.10.0/py36/CPU/sse2)
