### ISSUE TITLE
issue regarding mosaic decensoring

### ISSUE THREAD

**Issue by hoihoi007** [deeppomf/DeepCreamPy#57]
there's an issue that after running "decensor_mosaic", with original uncoloured, censored image in "decensor_input_original" and image with censored region coloured in "decensor_input", the output image is still the same as the original censored image. 
In other words, I can't get the "decensor_mosaic" to work. it just outputted the same image that I put into "decensor_input_original", no decensoring occurred

**Comment by deeppomf** [comment]
See [link](https://github.com/deeppomf/DeepCreamPy/blob/master/TROUBLESHOOTING.md)

**Comment by junh1024** [comment]
Also a possibility the green might be the wrong shade.
