### ISSUE TITLE
It's no issue, but I don't know where to type

### ISSUE THREAD

**Issue by BrokenDust** [deeppomf/DeepCreamPy#59]
Hi there,

I just tried the decensoring of the "original.jpg". So I edited it to the "original_painted.png" pic.
I overread the thing, that DeepCreamPy shoulnd't  used on nipples. Look at "decensored.png"

It seems that you code is running on nipples,

You can close or delete this.

[NSFW images were removed]

**Comment by deeppomf** [comment]
Do not post NSFW images.

It wasn't trained on nipples, but it can make good guesses.
