### ISSUE TITLE
AVX2 Error Binary

### ISSUE THREAD

**Issue by solowraith** [deeppomf/DeepCreamPy#66]
I'm having the same issue from #19 and I have tried using the solution found in #26 of uninstalling Python, removing the folder from Appdata\Local\Programs\Python, and then reinstalling python, then tensor and the requirements through pip. But even after all this I am still getting the AVX2 error when running the decensor.exe from both the 1.2.1 and the 1.2.3 Binary builds.

**Comment by deeppomf** [comment]
The solution in #26 doesn't work for the binary. It's meant for running the code yourself.
A binary build with support for non AVX CPUs will be available in the next update.
