### ISSUE TITLE
DeepCreamPy Not Working

### ISSUE THREAD

**Issue by DmitriyPekar** [deeppomf/DeepCreamPy#67]
cmd appears for a second and closes

https://i.imgur.com/FUrLXER.png

**Comment by junh1024** [comment]
You need to run from source since your CPU is non AVX. See https://github.com/deeppomf/DeepCreamPy/issues/26#issuecomment-434043166

**Comment by junh1024** [comment]
from source = from the .py

**Comment by DmitriyPekar** [comment]
another problem https://i.imgur.com/HHgLkwc.png

**Comment by Hipnotazer** [comment]
Same problem: 
OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I downloaded the latest model and put it in the "models" folder, but the problem did not solved

**Comment by Azradok** [comment]
I'm having the same problem (Mac OSX - Python3.6.7): 
OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I tried copying the model.h5 file from /original model/ and put it in /models/ but that didn't work either.

Suggestions?

**Comment by junh1024** [comment]
I'm willing 2 bet it's a user problem with current directory.

If you started your prompt in C:/windows, it will look there, not where deepcreampy is.

https://www.google.com/search?q=cmd+current+directory

**Comment by junh1024** [comment]
model.h5 in
DeepCreamPy\models\model.h5
?

**Comment by DmitriyPekar** [comment]
https://i.imgur.com/3E9fXOX.png

**Comment by junh1024** [comment]
I don't see model.h5 in there. see https://github.com/deeppomf/DeepCreamPy/blob/master/INSTALLATION.md#run-code-yourself
