### ISSUE TITLE
Decensor-mosaic doesn't run the script

### ISSUE THREAD

**Issue by Eismis-Gravas** [deeppomf/DeepCreamPy#69]
Anytime I try to use the decensor-mosaic shortcut to test out the mosaic decensor, the console opens up and closes with an error without doing anything - managed to snag a screenshot of the console righ before it closed https://puu.sh/BXt3f/10249ffc2e.jpg - the regular decensor.exe (tested with black bar image) works as intended.

Binary installation, Windows 10, used 1.2.2 version of program.

Looked around in issues, found a potential solution of making a .bat file - didn't work, same error with no result in the end - https://puu.sh/BXucU/3eb453f3ba.jpg

**Comment by unti1x** [comment]
You didn't create images with uncolored regions https://github.com/deeppomf/DeepCreamPy/blob/master/USAGE.md
