### ISSUE TITLE
Can not recovery hentai image censored

### ISSUE THREAD

**Issue by kidboo9** [deeppomf/DeepCreamPy#70]
I need to support feature recovery hentai images censored.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
More than that, you need grammar, spelling and altogether basic English lessons, mate. And the "not my native language" argument doesn't stand, says the present Baguette wielder.

**Comment by fen0s** [comment]
> More than that, you need grammar, spelling and altogether basic English lessons, mate. And the "not my native language" argument doesn't stand, says the present Baguette wielder.

Hey, can you please be less rude with people who you can't understand because of bad English skill? Maybe he started to learn English not so long ago, so he doesn't have too much skills, or he's using translate software.

**Comment by kidboo9** [comment]
Hello fen0s!
Sorry because I speak to English very bad. I hope your sympathy for this. I look at feature have to support Decensoring of ANY shaped censor but actually when I used to it wasn't decensored any image hentai. I hope you support me
Thank you!

**Comment by junh1024** [comment]
It already supports ANY shaped censor. Sometimes it just desn't work. Try another image with a smaller censor shape.

**Comment by junh1024** [comment]
Also, it needs to be a very exact shade of green. If it doesn't say "found 1 censored region" or similar you're doing it wrong.

**Comment by nhumanh69** [comment]
lol
