### ISSUE TITLE
Mosaic uncensor just copies the original into output

### ISSUE THREAD

**Issue by TheK0tYaRa** [deeppomf/DeepCreamPy#71]
Upon run it creates 1 to 1 recreation of pixelated origin image in the output folder. Tried multiple ones.
 Does the same thing.

Don't know how exactly to reproduce, tried it out only on hentai by now (cause why not).

I expected the image to be at least "melted" at the place where it was censored.

"DO NOT POST ADULT CONTENT." Mkay, will not do.

"Did you install DeepCreamPy with the binary?" Yep

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Version 1.2.3 beta app, 1083 windows
 - Supports AVX (yes)

**Comment by Kadantte** [comment]
You did what @deeppomf said on the USAGE.md ?!

## II. Decensoring mosaic censors

As with decensoring bar censors, perform the same steps of coloring the censored regions green and putting the colored image into the "decensor_input" folder.

In addition, move the original, uncolored images into the "decensor_input_original" folder. Ensure each original image has the same names as their corresponding colored version in the "decensor_input" folder.

For example, if the original image is called "mermaid.jpg," then you want to put this image in the "decensor_input_original" folder and, after you colored the censored regions, name the colored image "mermaid.png" and move it to the "decensor_input" folder.

### A. Using the binary

Decensor the images by double-clicking on the decensor_mosaic file.

### B. Running from scratch

Decensor the images by running

```
$ python decensor.py --is_mosaic=True
```

Decensored images will be saved to the "decensor_output" folder. Decensoring takes a few minutes per image.

**Comment by junh1024** [comment]
Your green needs to be exactly the right shade.

**Comment by TheK0tYaRa** [comment]
Yes, I have read other's issues before creating mine, because there iss no sence to create a dupe.
I have 100% green, no antialiasing coloring. And i have tried source. Not working as intended for me.

**Comment by junh1024** [comment]
It might not work https://github.com/deeppomf/DeepCreamPy/blob/master/TROUBLESHOOTING.md#poor-mosaic-decensoringsmosaic-decensoring-does-nothing

**Comment by TheK0tYaRa** [comment]
As wrotten before, i checked that part.

**Comment by koloved** [comment]
i have the same issue, it's just copy , nothing happens

**Comment by deeppomf** [comment]
@TheK0tYaRa @koloved Does bar decensoring work?
The updated model coming soon doesn't have the "do nothing issue," which was caused by failure to detect mosaic censors.

**Comment by devilemperor** [comment]
I did some tests.
Mosaic uncensor doesn't work if the mosaic looks blurred.

**Comment by TheK0tYaRa** [comment]
> Does bar decensoring work?

Kinda. It's not what it's exactly supposed to be, but at least it's near the goal.

**Comment by TheK0tYaRa** [comment]
To be exact - that was a circle censor thing with no pixelating

**Comment by TheK0tYaRa** [comment]
> Mosaic uncensor doesn't work if the mosaic looks blurred.

Nah, it's not blurred. i tried re-censoring it after it failed. The result is still original image.
