### ISSUE TITLE
Is there a specific green color to use?

### ISSUE THREAD

**Issue by Ftwpker** [deeppomf/DeepCreamPy#77]
I am toying around with an image using some image editor tool on mac called Paint S. I have it in a light green similar to the example but when running the program, it is saying no green regions detected.

**Comment by TehNut** [comment]
It should be `0, 255, 0` RGB or `#00FF00` hex.

**Comment by Wuestengecko** [comment]
All you need to know (and some helpful advice) can be found in the [Usage Instructions](https://github.com/deeppomf/DeepCreamPy/blob/master/USAGE.md) and [Troubleshooting tips](https://github.com/deeppomf/DeepCreamPy/blob/master/TROUBLESHOOTING.md).

**Comment by daipiaoxiang** [comment]
think you
