### ISSUE TITLE
Problem while running it on Kali Linux

### ISSUE THREAD

**Issue by deadfishhackers** [deeppomf/DeepCreamPy#78]
Does anyone know how to fix this?

   root@brunnyinc ~ pip install tensorflow-1.10.0-cp36-cp36m-win_amd64.whl
**Requirement 'tensorflow-1.10.0-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist**
I tried "pip install -r requirements.txt" but it didnt work i also tried this 2 "pip3 install -r requirements.txt" and "pip2 install -r requirements.txt" none of them worked 
after trying to install it with PIP i got this error

**Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

Can anyone help me?

**Comment by noirscape** [comment]
- `python3 -m venv venv`
- `source venv/bin/activate`
- `pip3 install -r requirements`

Then in all terminal sessions before running the script do `source venv/bin/activate` when in the deepcreampy directory.

**Comment by deadfishhackers** [comment]
*i did all the steps but when i did pip3 install -r requirements.txt i got
this*

































































*  root@brunnyinc ~ pip3 install -r requirements.txtCollecting
tensorflow==1.10.0 (from -r requirements.txt (line 1))  Cache entry
deserialization failed, entry ignored  Downloading
https://files.pythonhosted.org/packages/ee/e6/a6d371306c23c2b01cd2cb38909673d17ddd388d9e4b3c0f6602bfd972c8/tensorflow-1.10.0-cp36-cp36m-manylinux1_x86_64.whl
<https://files.pythonhosted.org/packages/ee/e6/a6d371306c23c2b01cd2cb38909673d17ddd388d9e4b3c0f6602bfd972c8/tensorflow-1.10.0-cp36-cp36m-manylinux1_x86_64.whl>
(58.4MB)    70% |██████████████████████▊         | 41.5MB 25kB/s eta
0:10:54Exception:Traceback (most recent call last):  File
"/root/venv/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py",
line 302, in _error_catcher    yield  File
"/root/venv/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py",
line 384, in read    data = self._fp.read(amt)  File
"/root/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py",
line 60, in read    data = self.__fp.read(amt)  File
"/usr/lib/python3.6/http/client.py", line 449, in read    n =
self.readinto(b)  File "/usr/lib/python3.6/http/client.py", line 493, in
readinto    n = self.fp.readinto(b)  File "/usr/lib/python3.6/socket.py",
line 586, in readinto    return self._sock.recv_into(b)  File
"/usr/lib/python3.6/ssl.py", line 1009, in recv_into    return
self.read(nbytes, buffer)  File "/usr/lib/python3.6/ssl.py", line 871, in
read    return self._sslobj.read(len, buffer)  File
"/usr/lib/python3.6/ssl.py", line 631, in read    v =
self._sslobj.read(len, buffer)socket.timeout: The read operation timed
outDuring handling of the above exception, another exception
occurred:Traceback (most recent call last):  File
"/root/venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in
main    status = self.run(options, args)  File
"/root/venv/lib/python3.6/site-packages/pip/commands/install.py", line 353,
in run    wb.build(autobuilding=True)  File
"/root/venv/lib/python3.6/site-packages/pip/wheel.py", line 749, in
build    self.requirement_set.prepare_files(self.finder)  File
"/root/venv/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in
prepare_files    ignore_dependencies=self.ignore_dependencies))  File
"/root/venv/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in
_prepare_file    session=self.session, hashes=hashes)  File
"/root/venv/lib/python3.6/site-packages/pip/download.py", line 821, in
unpack_url    hashes=hashes  File
"/root/venv/lib/python3.6/site-packages/pip/download.py", line 659, in
unpack_http_url    hashes)  File
"/root/venv/lib/python3.6/site-packages/pip/download.py", line 882, in
_download_http_url    _download_url(resp, link, content_file, hashes)  File
"/root/venv/lib/python3.6/site-packages/pip/download.py", line 603, in
_download_url    hashes.check_against_chunks(downloaded_chunks)  File
"/root/venv/lib/python3.6/site-packages/pip/utils/hashes.py", line 46, in
check_against_chunks    for chunk in chunks:  File
"/root/venv/lib/python3.6/site-packages/pip/download.py", line 571, in
written_chunks    for chunk in chunks:  File
"/root/venv/lib/python3.6/site-packages/pip/utils/ui.py", line 139, in
iter    for x in it:  File
"/root/venv/lib/python3.6/site-packages/pip/download.py", line 560, in
resp_read    decode_content=False):  File
"/root/venv/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py",
line 436, in stream    data = self.read(amt=amt,
decode_content=decode_content)  File
"/root/venv/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py",
line 401, in read    raise IncompleteRead(self._fp_bytes_read,
self.length_remaining)  File "/usr/lib/python3.6/contextlib.py", line 99,
in __exit__    self.gen.throw(type, value, traceback)  File
"/root/venv/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py",
line 307, in _error_catcher    raise ReadTimeoutError(self._pool, None,
'Read timed out.')urllib3.exceptions.ReadTimeoutError:
HTTPSConnectionPool(host='files.pythonhosted.org
<http://files.pythonhosted.org>', port=443): Read timed out. *

**Comment by Yukariin** [comment]
Check your Internet connection.
