### ISSUE TITLE
Kaggle

### ISSUE THREAD

**Issue by Kadantte** [deeppomf/DeepCreamPy#79]
Is it possible to run DCP at [Kaggle](https://Kaggle.com) ?!

**Comment by Walkman100** [comment]
It seems like a project-based site for machine learning models and running them on specific datasets, I doubt it would help to put a project there unless you need another host for the program itself

**Comment by deeppomf** [comment]
No. Don't see an easy way for users to upload their files to Kaggle. Kaggle doesn't want porn on their website.
