### ISSUE TITLE
Slit type decensor improvement

### ISSUE THREAD

**Issue by sanscriptum** [deeppomf/DeepCreamPy#80]
Currently DCP seems to handle slits rather poorly. It just doesn't know what to do when there's not a lot of material to work with, ie when censor bar covers the entire length. Most of the time it just applies skintone or gives up halfway. Can something be done about this? This might also potentially help with sticker-type censoring which covers vagina completely.  

Here's couple of NSFW examples to work with:  
pixiv.net/member_illust.php?mode=medium&illust_id=67919841    (Example with semi-transparent bar)  
pixiv.net/member_illust.php?mode=medium&illust_id=59080807   (Example with "puffy" type slit)  

I was thinking maybe if there was a ``decensor_input_original`` folder support for regular decensors, maybe it could help? Sometimes marked area might cover too much and if it sees the original, it might improve the result.

**Comment by deeppomf** [comment]
Don't think so. Coloring marks areas the neural network can completely ignore. Having the decensor_input_original folder wouldn't help regular decensors.
I am developing methods for better decensors when the vagina is heavily censored.

**Comment by sanscriptum** [comment]
Is it a bug that sometimes the coloring might be off a bit (usually darker) at the upper edges? It gets the content almost perfectly, but uneven coloring makes it stand out noticeably.

**Comment by deeppomf** [comment]
I think that's a problem with the network and isn't easy to solve.
