### ISSUE TITLE
Can I change the Green color to the color I want?

### ISSUE THREAD

**Issue by sherry122232** [deeppomf/DeepCreamPy#83]
I wonder if I can change the code then I can detect the color is not green but other color?
IF I can, how can I do this?

**Comment by deeppomf** [comment]
Change this line https://github.com/deeppomf/DeepCreamPy/blob/8d9dc013ef4e893707acb1d4ae3070760a4f1acb/libs/utils.py#L127 to the color values you want.

**Comment by sherry122232** [comment]
Thanks very much.

**Comment by sherry122232** [comment]
I've changed it as you said, it just detects the region but cannot change the masaic to the origin. How can I do?? Should I retrained the model? Thanks a lot.

**Comment by sanscriptum** [comment]
I thought you could just use ``--mask_color_red`` ``--mask_color_green`` ``--mask_color_blue`` arguments, no?

**Comment by deeppomf** [comment]
@sherry122232 You need to change config.py too
I'll fix the code so you only need to change config.

**Comment by Kadantte** [comment]
On config.py u need to change this to your color
```python
	#Decensor settings
	parser.add_argument('--mask_color_red', dest='mask_color_red', default=0, help='red channel of mask color in decensoring')
	parser.add_argument('--mask_color_green', dest='mask_color_green', default=255, help='green channel of mask color in decensoring')
	parser.add_argument('--mask_color_blue', dest='mask_color_blue', default=0, help='blue channel of mask color in decensoring')
```
