### ISSUE TITLE
deepcreampy opened but closing after without sending any decensored hentai...

### ISSUE THREAD

**Issue by Dinoguy12** [deeppomf/DeepCreamPy#89]
i need help, im using an 64-bit computer to decensor hentai, im using paint.net  to color to the right color, i putted it in the decensor_input, i clicked on the application, it open for a few sec, but it close after and doesnt send any decensored hentai. help me

**Comment by Dinoguy12** [comment]
![image](https://user-images.githubusercontent.com/33851711/48922473-d8758e80-ee74-11e8-941c-b4d47976126d.png)

**Comment by deeppomf** [comment]
See https://github.com/deeppomf/DeepCreamPy/issues/52
Did you install https://www.microsoft.com/en-us/download/details.aspx?id=53587 ?
