### ISSUE TITLE
How to remove DeepCreamPy on ubuntu 18.04?

### ISSUE THREAD

**Issue by senior-developers** [deeppomf/DeepCreamPy#92]
When I install DCP, I used sudo + command, maybe will cause something to System, so I want to remove it and reinstall

**Comment by Wuestengecko** [comment]
DCP itself doesn't go anywhere outside of its git repo. However if you grab its dependencies, these will be installed system-wide by default.

You can list all pip-managed packages with `pip list`. Cross-check these with the `requirements.txt`, and you should be able to `pip uninstall` them. Passing `--not-required` to `pip list` might help.
