### ISSUE TITLE
Visualizer DCP Model [Netron]

### ISSUE THREAD

**Issue by Kadantte** [deeppomf/DeepCreamPy#97]
Is there a way how to visualizer DCP Model on [Netron](https://github.com/lutzroeder/netron) i try it but there is an error.

![image](https://user-images.githubusercontent.com/11579313/50382524-6ffb1680-0699-11e9-93f5-97d321d374b1.png)

**Comment by deeppomf** [comment]
Might be because DCP uses some custom modules.
